/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import DAL.DisciplinaDAO;
import DAL.MateriaDAO;
import DAL.QuestaoDAO;
import Model.Disciplina;
import Model.Materia;
import Model.Questao;
import Model.Resposta;
import java.awt.HeadlessException;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Marina.Silva
 */
public class AddQuestionJFrame extends javax.swing.JFrame {

    /**
     * Creates new form AddQuestionJFrame
     */
    private Questao questao;

    public AddQuestionJFrame() {
        initComponents();
        loadDisciplinas();
        loadBimestres();
        
        questao = new Questao();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cmbDisciplina = new javax.swing.JComboBox();
        cmbMateria = new javax.swing.JComboBox();
        cmbBimestre = new javax.swing.JComboBox();
        btnAddAnswer = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableRespostas = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtQuestion = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Adição de Questões");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Bimestre:");

        jLabel2.setText("Disciplina:");

        jLabel3.setText("Matéria:");

        jLabel4.setText("Questionamento:");

        cmbDisciplina.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbDisciplina.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbDisciplinaItemStateChanged(evt);
            }
        });

        cmbMateria.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbBimestre.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnAddAnswer.setText("Adicionar Resposta");
        btnAddAnswer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddAnswerActionPerformed(evt);
            }
        });

        jLabel5.setText("Respostas:");

        jTableRespostas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Conteúdo", "Correta"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableRespostas);
        if (jTableRespostas.getColumnModel().getColumnCount() > 0) {
            jTableRespostas.getColumnModel().getColumn(0).setResizable(false);
            jTableRespostas.getColumnModel().getColumn(0).setPreferredWidth(200);
            jTableRespostas.getColumnModel().getColumn(1).setResizable(false);
            jTableRespostas.getColumnModel().getColumn(1).setPreferredWidth(5);
        }

        jButton2.setText("Salvar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Cancelar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        txtQuestion.setColumns(15);
        txtQuestion.setLineWrap(true);
        txtQuestion.setRows(5);
        jScrollPane2.setViewportView(txtQuestion);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAddAnswer, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbMateria, 0, 126, Short.MAX_VALUE)
                            .addComponent(cmbDisciplina, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbBimestre, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(cmbBimestre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAddAnswer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddAnswerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAnswerActionPerformed
        AddAnswerJFrame addAnswer = new AddAnswerJFrame();
        addAnswer.setLocationRelativeTo(this);
        addAnswer.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        addAnswer.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                //Até aqui está perfeito, vamos ver se funciona uaheuae

                //Blz, agora quando o frame for fechado, pego o objeto que o user preencheu
                if (addAnswer.getResposta() != null) {
                    Resposta resposta = addAnswer.getResposta();
                    questao.addAnswer(resposta);
                    JOptionPane.showMessageDialog(rootPane, "Adicionado com sucesso!", getTitle(), JOptionPane.INFORMATION_MESSAGE);
                }
                UpdateJTableRespostas();
            }

        });

        //Atualizar as paradinhas tudo.
        addAnswer.setVisible(true);
    }//GEN-LAST:event_btnAddAnswerActionPerformed
    private void UpdateJTableRespostas() {
        ArrayList<Resposta> answerList = questao.getRespostas();
        ArrayList<String> columns = new ArrayList<>();
        ArrayList<String[]> values = new ArrayList<>();
        columns.add("Resposta");
        columns.add("Correta");

        answerList.stream().forEach((Resposta r) -> {
            values.add(new String[]{r.getResposta(), String.valueOf(r.isCorreta())});
        });
    }
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        if (cmbDisciplina.getItemCount() <= 0) {
            return;
        }
        Disciplina d = (Disciplina) cmbDisciplina.getSelectedItem();
        loadMaterias(d.getId());
    }//GEN-LAST:event_formWindowOpened

    private void cmbDisciplinaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbDisciplinaItemStateChanged
        if (cmbDisciplina.getItemCount() != 0) {
            Disciplina d = (Disciplina) cmbDisciplina.getSelectedItem();
            loadMaterias(d.getId());
        }
    }//GEN-LAST:event_cmbDisciplinaItemStateChanged

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            Questao q = new Questao();
            QuestaoDAO questão = new QuestaoDAO();
            q.setBimestre(cmbBimestre.getSelectedIndex());
            q.setIdMateria(((Materia) cmbMateria.getSelectedItem()).getId());
            q.setPergunta(txtQuestion.getText());
            if (questão.insert(q) != -1) {
                JOptionPane.showMessageDialog(this, "Questão inserida com sucesso!");
            } else {
                JOptionPane.showMessageDialog(this, "Falha ao inserir!");
            }
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(this, "Falha ao inserir a questão: " + e);
        }
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddQuestionJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddQuestionJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddQuestionJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddQuestionJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new AddQuestionJFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddAnswer;
    private javax.swing.JComboBox cmbBimestre;
    private javax.swing.JComboBox cmbDisciplina;
    private javax.swing.JComboBox cmbMateria;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableRespostas;
    private javax.swing.JTextArea txtQuestion;
    // End of variables declaration//GEN-END:variables

    private void loadDisciplinas() {
        cmbDisciplina.removeAllItems();
        DisciplinaDAO disciplina = new DisciplinaDAO();
        ArrayList<Disciplina> disciplinaList = disciplina.retrieveAll();
        disciplinaList.stream().forEach((disciplina1) -> {
            cmbDisciplina.addItem(disciplina1);
        });
    }

    private void loadMaterias(int id) {
        cmbMateria.removeAllItems();
        MateriaDAO materia = new MateriaDAO();
        ArrayList<Materia> materiaList = materia.retrieveAllByDisciplina(id);
        materiaList.stream().forEach((materia1) -> {
            cmbMateria.addItem(materia1);
        });
    }

    private void loadBimestres() {
        cmbBimestre.removeAllItems();
        cmbBimestre.addItem("1º");
        cmbBimestre.addItem("2º");
        cmbBimestre.addItem("3º");
        cmbBimestre.addItem("4º");
    }
}
