/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import DAL.DisciplinaDAO;
import DAL.MateriaDAO;
import DAL.TesteDAO;
import Model.Disciplina;
import Model.Materia;
import Model.Teste;
import java.awt.HeadlessException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;

public class AddTesteJFrame extends javax.swing.JFrame {

    int insert;
    Teste t = new Teste();

    public AddTesteJFrame() {
        initComponents();
        loadDisciplinas();
        insert = 1;
        cmbMateria.removeAllItems();
    }

    public AddTesteJFrame(Teste teste) {
        initComponents();
        btnAdd.setText("Editar");
        txtNumeroQuestoes.setText(String.valueOf(teste.getNumeroQuestoes()));
        loadDisciplinas();
        cmbDisciplina.setSelectedItem(teste.getDisciplina().getNome());
        txtDataGeracao.setText(new SimpleDateFormat("dd/MM/yyyy").format(teste.getDataGeracao())); //DATA, eu te odeio!! Mas eu consegui.. #CHUUUPAA
        insert = 2;
        cmbMateria.removeAllItems();
        t.setId(teste.getId());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cmbDisciplina = new javax.swing.JComboBox();
        txtDataGeracao = new javax.swing.JTextField();
        txtNumeroQuestoes = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cmbMateria = new javax.swing.JComboBox();
        btnAdd = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Adição de Testes");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Teste", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("sansserif", 1, 12), new java.awt.Color(153, 51, 255))); // NOI18N

        jLabel1.setText("Disciplina:");

        jLabel2.setText("Data de Geração:");

        jLabel3.setText("Número de questões:");

        cmbDisciplina.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbDisciplina.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbDisciplinaItemStateChanged(evt);
            }
        });

        jLabel4.setText("Matéria:");

        cmbMateria.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDataGeracao))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNumeroQuestoes))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmbMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmbMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtDataGeracao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNumeroQuestoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        btnAdd.setText("Gerar");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancelar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAdd)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnCancel)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        
        TesteDAO teste = new TesteDAO();
        SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");
        if (insert == 1) { //valor 1 para inserir novo teste, valor 2 para editar
            try {
                t.setDisciplina(((Disciplina) cmbDisciplina.getSelectedItem())); //CONFERIR
                t.setMateria((Materia) cmbMateria.getSelectedItem());
                t.setDataGeracao(new java.sql.Date(format.parse(txtDataGeracao.getText()).getTime()));
                t.setNumeroQuestoes(Integer.parseInt(txtNumeroQuestoes.getText()));
                if (teste.insert(t) != -1) {
                    JOptionPane.showMessageDialog(this, "Teste inserido com sucesso!!");
                } else {
                    JOptionPane.showMessageDialog(this, "Falha ao inserir.");
                }
            } catch (HeadlessException | NumberFormatException | ParseException e) {
                JOptionPane.showMessageDialog(this, "Falha ao adicionar novo teste: " + e);
            }
        } else {
            try {
                t.setDisciplina(((Disciplina) cmbDisciplina.getSelectedItem()));
                t.setMateria((Materia) cmbMateria.getSelectedItem());
                t.setDataGeracao(new java.sql.Date(format.parse(txtDataGeracao.getText()).getTime()));
                t.setNumeroQuestoes(Integer.parseInt(txtNumeroQuestoes.getText()));
                if (teste.update(t) != -1) {
                    JOptionPane.showMessageDialog(this, "Teste editado com sucesso!");
                } else {
                    JOptionPane.showMessageDialog(this, "Falha ao editar teste.");
                }
            } catch (NumberFormatException | ParseException e) {
                JOptionPane.showMessageDialog(this, "Falha ao editar: " + e);
            }
        }
        this.dispose();
    }//GEN-LAST:event_btnAddActionPerformed

    private void cmbDisciplinaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbDisciplinaItemStateChanged
        if (cmbDisciplina.getItemCount() != 0) {
            Disciplina d = (Disciplina) cmbDisciplina.getSelectedItem();
            loadMaterias(d.getId());
        }
    }//GEN-LAST:event_cmbDisciplinaItemStateChanged

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        Disciplina d = (Disciplina) cmbDisciplina.getSelectedItem();
        loadMaterias(d.getId());
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddTesteJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new AddTesteJFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCancel;
    private javax.swing.JComboBox cmbDisciplina;
    private javax.swing.JComboBox cmbMateria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtDataGeracao;
    private javax.swing.JTextField txtNumeroQuestoes;
    // End of variables declaration//GEN-END:variables

    private void loadDisciplinas() {
        cmbDisciplina.removeAllItems();
        DisciplinaDAO disciplina = new DisciplinaDAO();
        ArrayList<Disciplina> disciplinaList = disciplina.retrieveAll();
        disciplinaList.stream().forEach((disciplina1) -> {
            cmbDisciplina.addItem(disciplina1);
        });
    }

    private void loadMaterias(int id) {
        cmbMateria.removeAllItems();
        MateriaDAO materia = new MateriaDAO();
        ArrayList<Materia> materiaList = materia.retrieveAllByDisciplina(id);
        materiaList.stream().forEach((materia1) -> {
            cmbMateria.addItem(materia1);
        });
    }

}
